# -*- coding: utf-8 -*-
"""Day-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sgNX8110EcJhEO2l2dRdObXat91y6Yvk
"""

def div(a, b):
  print(b / a)

def div_rev(fun):
  
  def inner(a, b):
    if a > b:
      a, b = b, a
    fun(a, b)    
 
  return inner

div = div_rev(div) 

div(4, 2)